id: P006611
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137858
  title: གནའ་གྲོང་།
  author: ''
  volumes:
    884a1e4b3b09488eacab5e0b6b7168bf:
      image_group_id: I2PD18255
      title: ''
      volume_number: 1
      total_pages: 350
